package pe.archety;

public enum BatchWriterServiceAction {
    CREATE_IDENTITY,
    CREATE_IDENTITY_AND_RELATIONSHIP,
    CREATE_PAGE,
    CREATE_PAGE_AND_RELATIONSHIP,
    CREATE_BOTH,
    CREATE_RELATIONSHIP
}
