package pe.archety;

public enum BatchWriterServiceAction {
    CREATE_IDENTITY,
    CREATE_IDENTITY_AND_LIKES_RELATIONSHIP,
    CREATE_IDENTITY_AND_HATES_RELATIONSHIP,
    CREATE_IDENTITY_WITH_TOKEN,
    CREATE_TOKEN,

    CREATE_PAGE,
    CREATE_PAGE_AND_LIKES_RELATIONSHIP,
    CREATE_PAGE_AND_HATES_RELATIONSHIP,

    CREATE_BOTH_AND_LIKES_RELATIONSHIP,
    CREATE_BOTH_AND_HATES_RELATIONSHIP,

    CREATE_LIKES_RELATIONSHIP,
    CREATE_HATES_RELATIONSHIP,

    CREATE_IDENTITY_AND_KNOWS_RELATIONSHIP,
    CREATE_2ND_IDENTITY_AND_KNOWS_RELATIONSHIP,
    CREATE_BOTH_AND_KNOWS_RELATIONSHIP,
    CREATE_KNOWS_RELATIONSHIP
}
